### ISSUE TITLE
R14 power rating

### ISSUE THREAD

**Issue by roor** [osannolik/MotCtrl#2]
Hello, i find your design quite fascinating, and trying to build something similar. I have question about gate resistors power rating.
In my math it is look like:
Gate voltage is 12V
Gate resistor 4.7Ohm
I_g_resistor = V/R = 12/4.7 = 2.55A
P= I^2*R = 30.56W

Is it correct and do you use such power resistor or it is acceptable to use lower power rating resistor for gates?

thank you for response

**Comment by osannolik** [comment]
Your calculation is not quite correct. You will get (approximately) the peak power just as the gate is turned on. For these types of resistors this peak current is no problem assuming it is for such a short duration. 
Instead, you need to worry about the average power dissipation. It is something like:
P = Vgs * Qg * fsw
For this hw and using a switching frequency 20 kHz gives a power dissipation of about 12 V * 170 nC * 20 kHz = 40 mW. I am currently using a resistor rated for 1/16 W.

**Comment by roor** [comment]
Thnx a lot, i knew there was something wrong, since it is just abnormally high power fur such an easy job.
