### ISSUE TITLE
low power STM32 MCU

### ISSUE THREAD

**Issue by mkeyno** [osannolik/MotCtrl#3]
sorry for open ticket for my question 
I was wondering if these code sources could be ported for lower MCU such as STM32F103 series?
if so what would the penalty for the features?

**Comment by osannolik** [comment]
The main issue that might cause performance penalty would be if you use an MCU without FPU. However, if I remember correctly I think the early versions of the VESC used floating point arithmetics in the current control loop on an Cortex-M3 without FPU, so I guess it could work.
