### ISSUE TITLE
estimation of total price BOM

### ISSUE THREAD

**Issue by nathmo** [osannolik/MotCtrl#4]
hi there, i'm comparing open sources brushless design.
Would you have an estimation of the price to build one ?
 i'm looking for a price range so that i compare it to the others i've found. (and it might be nice to put in the specs list)

many thanks in advance

**Comment by osannolik** [comment]
The most expensive parts (mcu, fets, current sense etc) sum to approx 90 USD. Adding the rest (passives and cheaper stuff) and cost of manufacturing the pcb I would estimate the total cost to be around 150-200 USD. That is for a one-off build, the cost per unit of course depend on quantity. 

However, if you are looking for a tried and proven design to actually build I do not recommend this one. It was a personal hobby project for learning these kind of things and it has not been used in any real world applications.

**Comment by nathmo** [comment]
Thanks a lot for the answer. (I probably won't build one. It's just to get an idea of what design exist, what works, what does not and what is worth what price) yours has a few interesting ideas like the current sensing that I didn't see in much design, but it is quite expensive (event tho the price do tend to drop if I make more than one copy)
